@echo off
title Sortret APK Builder
echo ==============================================
echo          BUILDING SORTRET APK v2.8
echo ==============================================
echo.

:: Automatically detect Android Studio's JBR (JDK 17/21)
if exist "C:\Program Files\Android\Android Studio\jbr\bin\java.exe" (
    set "JAVA_HOME=C:\Program Files\Android\Android Studio\jbr"
    echo [INFO] Using Android Studio JDK at: %JAVA_HOME%
) else if not "%JAVA_HOME%"=="" (
    echo [INFO] Using custom JAVA_HOME: %JAVA_HOME%
) else (
    echo [WARNING] JDK was not found. Please make sure Android Studio is installed at standard location or JAVA_HOME is set.
)

if not "%JAVA_HOME%"=="" (
    set "PATH=%JAVA_HOME%\bin;%PATH%"
)

:: Automatically detect Android SDK and create local.properties if it doesn't exist
if not exist "local.properties" (
    if exist "%LOCALAPPDATA%\Android\Sdk" (
        echo [INFO] Creating local.properties with SDK path...
        echo # Generated by builder > local.properties
        echo sdk.dir=C\:\\Users\\%USERNAME%\\AppData\\Local\\Android\\Sdk >> local.properties
    ) else (
        echo [WARNING] Android SDK not found at standard path. Please configure it manually in local.properties.
    )
)

echo [1/3] Cleaning and compiling APK...
call gradlew.bat clean assembleDebug
if %ERRORLEVEL% neq 0 (
    echo.
    echo [ERROR] Build failed!
    pause
    exit /b %ERRORLEVEL%
)
echo.

echo [2/3] Exporting APK to project root...
if exist "app\build\outputs\apk\debug\app-debug.apk" (
    copy "app\build\outputs\apk\debug\app-debug.apk" "Sortret_v2.8.apk" > nul
    echo [SUCCESS] APK compiled and saved as: Sortret_v2.8.apk
) else (
    echo [ERROR] Compiled APK not found in build outputs.
    pause
    exit /b 1
)
echo.

echo [3/3] Installing APK to connected device (preserving data)...
echo Checking for connected devices...
adb devices
echo.
echo Installing Sortret_v2.8.apk...
adb install -r Sortret_v2.8.apk
if %ERRORLEVEL% neq 0 (
    echo.
    echo [WARNING] Installation failed or no device found.
    echo Make sure USB debugging is enabled on your device.
) else (
    echo.
    echo [SUCCESS] APK successfully installed on device with data preserved!
)
echo.
pause
